version: '3.9'

services:
  db:
    image: "postgres:14.0-alpine"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skeleton
    ports:
      - "5435:5432"

volumes :
  app-volume: #
